runtime: custom
env: flex

instance_class: F1

service: customer-management-frontend


env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
  - url: /.*
    script: ignore
    secure: always

