runtime: custom
env: flex

instance_class: F1

service: customer-core

env_variables:
  SERVER_PORT: 8080
  SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
  SPRING_DATASOURCE_URL: jdbc:mysql://34.71.44.212:3306/customer-core
  SPRING_DATASOURCE_USERNAME: lakesiduemutual-user
  SPRING_DATASOURCE_PASSWORD: e00BalPy<E3$+qyZ

